Operations to perform:
  Apply all migrations: ParticipantDB, admin, auth, contenttypes, sessions
Running migrations:
  Applying ParticipantDB.0014_auto_20180920_1228...Traceback (most recent call last):
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'skill'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 495, in alter_field
    new_db_params = new_field.db_parameters(connection=self.connection)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/models/fields/related.py", line 966, in db_parameters
    return {"type": self.db_type(connection), "check": self.db_check(connection)}
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/models/fields/related.py", line 963, in db_type
    return self.target_field.rel_db_type(connection=connection)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/models/fields/related.py", line 878, in target_field
    return self.foreign_related_fields[0]
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/models/fields/related.py", line 632, in foreign_related_fields
    return tuple(rhs_field for lhs_field, rhs_field in self.related_fields if rhs_field)
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/models/fields/related.py", line 619, in related_fields
    self._related_fields = self.resolve_related_fields()
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/models/fields/related.py", line 612, in resolve_related_fields
    else self.remote_field.model._meta.get_field(to_field_name))
  File "/home/lingtech/.virtualenvs/ling-db-dev/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Musical_Skill has no field named 'skill'
